### PR TITLE
Character picker availability

### PR DESCRIPTION
**Pull request by vitork**
We're letting Eagle decide when the character picker should be available.

### CODE REVIEW

**Comment by metade** [comment]
Why would we need to an environment variable to control this? Isn't all the data we need in LMN assets? I just think it's better to have 1 place where character picker is configured.

**Comment by vitork** [comment]
I agree that's better to configure that in just one place, but the data we need is not in lmn-assets as you mentioned. I commented here: https://github.com/Lostmyname/eagle/pull/2906#issuecomment-154139339

That's why I chose this approach. Otherwise we would have to change lmn-assets to include that info, change chameleon to return that info, and change monkey to read that info. And to add the character picker to a new locale, we would have to update lmn-assets and bump the version on chameleon (and maybe also on eagle and chameleon for consistency sake).

The way I'm proposing, we'd just need to update an ENV var on eagle.

**Comment by metade** [comment]
> but the data we need is not in lmn-assets as you mentioned

Surely the availability of the character picker feature is based on what assets there are available in that language? And that information lives in `lmn-assets` already.

Maybe we need to get on a call to discuss this.

**Comment by vitork** [comment]
@metade Yeah, indeed that information (assets available in a language) is on `lmn-assets` and we wouldn't even need to activate/deactivate the character picker. We could just show the selector for every language that has multiple stories for a single letter.

But for some reason (maybe marketing/testing purposes) the character picker is not being released to all languages in that way. I think is Jobina who decides which language should have the character picker enabled, that's why we need this enable/disable feature.

**Comment by jobina1** [comment]
Hey Guys

Yep that’s correct - it depends on the language, but generally once we have a choice for half the alphabet or more, we decide to turn on character picker.

So if this helps somehow, this could be decided in an automatic way, but it does sort of depend on which letters and which language they are. Not that important if u v w x y z has only one, but we definitely don’t want character picker on if it’s going to highlight the fact that we only have one of a popular letter in that language e.g. a e l o… So it’s fairly finger in the air whether we choose to turn it on or not at the moment.

J

-- 
Jobina Hardy
Product Manager
07834 084 343
www.lostmy.name  <http://www.lostmy.name/>

Looking for a new challenge? ​We're hiring! <http://making.lostmy.name/>

Looking for a new book? We’ve got something secret and special on the way! <https://www.lostmy.name/something-new>

facebook.com/lostmynamebook
twitter.com/Lostmynamebook

**Comment by metade** [comment]
Fair enough - I thought there was some specific configuration that had to be added to `lmn-assets` to make character picker work. If it's just based on the number of stories that's available then I can understand why we'd want to have control over when we make it available for a particular language.

In this case I think I would prefer for the choice of whether it's enabled to live in Eagle, either as an ENV_VAR or just in code. I think Monkey should just look for a `show-char-picker` data attribute - I don't think we want to include the list of locales here.

**Comment by mrcthms** [comment]
FE code looks :+1:

**Comment by vitork** [comment]
Thanks @mrcthms!

**Pull request merged**
