### PR TITLE
Feature/heidelberg update

### PR DESCRIPTION
**Pull request by karimbeyrouti**
- Switch monkey to use latest updates to heidelberg, which make it compatible with JHome, fixes a bug with IE10, and reduces flickering with turning pages on some GPU configurations 

- Use LMN/heidelberg branch instead of DJGrant's branch

### CODE REVIEW

**Comment by callumacrae** [comment]
It would be better to do a release instead of pointing to the github repository

**Comment by karimbeyrouti** [comment]
Agreed - however I was not sure how you handle it internally with private repo's .

**Comment by barneyfoxuk** [comment]
@callumacrae good to go now?

**Comment by callumacrae** [comment]
The version number is going down

This PR is the perfect example of why you shouldn't increase the version number in anywhere but master :D

**Comment by barneyfoxuk** [comment]
Ha, your so right.

I'll remove the version update to monkey, merge and then update the version on master

**Comment by karimbeyrouti** [comment]
Sweet ! - note: the aim of this Heidelberg update was to get 100% parity with LMN book, and fix as much as possible in the time I had left for JHome. 

There are still some small issues with JHome / single spreads when using slider / navigating to a specific page. 

Sadly I ran out of time to have a proper look at those little niggly issues with single spreads. But it is a good improvement on the current version .

**Pull request merged**
