### PR TITLE
Hotfix/get rid of the wiggle

### PR DESCRIPTION
**Pull request by barneyfoxuk**
Replaced the wiggle and brown bg with a white spinner

Needs to go live with:
https://github.com/Lostmyname/eagle/pull/1711

### CODE REVIEW

**Comment by callumacrae** [comment]
in the future, please don't make versions in branches, merge changes into master and then release from master :)

**Comment by callumacrae** [comment]
I didn't even notice this, but this is why:

screen shot 2015-06-17 at 16 54 14

**Comment by barneyfoxuk** [comment]
Version 4.4.6 hadn't been pushed.  Should be OK now?

**Comment by callumacrae** [comment]
Yeah you released it as 4.4.7. But the log is confusing now, would have been better to wait until merged into master before tagging it

**Comment by barneyfoxuk** [comment]
Will do next time

**Comment by callumacrae** [comment]
:smile: :tada:

**Pull request merged**
